version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestProjectDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
